# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablemodel',
            name='semester',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
